In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv('../dataset/processed/train.csv', index_col='PassengerId')
test_df = pd.read_csv('../dataset/processed/test.csv', index_col='PassengerId')

In [3]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()

In [4]:
print(X.shape, y.shape)

(891, 32) (891,)


In [5]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [6]:
print('mean survival in train : {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test : {0:.3f}'.format(np.mean(y_test)))

mean survival in train : 0.383
mean survival in test : 0.385


In [7]:
import sklearn
sklearn.__version__

'0.19.1'

In [8]:
from sklearn.dummy import DummyClassifier

In [9]:
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [10]:
# train model
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [11]:
print('score for baseline model : {0:.2f}'.format(model_dummy.score(X_test, y_test)))

score for baseline model : 0.61


In [12]:
# peformance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [13]:
# accuracy score
print('accuracy for baseline model : {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

accuracy for baseline model : 0.61


In [14]:
print('confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))

confusion matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [15]:
# precision and recall scores
print('precision for baseline model : {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('recall for baseline model : {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

precision for baseline model : 0.00
recall for baseline model : 0.00


/Users/suryasingh/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
# kaggle Submission

In [17]:
# converting to the matrix
test_X = test_df.as_matrix().astype('float')

In [18]:
# get predictions
predictions = model_dummy.predict(test_X)

In [19]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions} )

In [20]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [21]:
submission_data_path = '../dataset/external'
submission_file_path = '../dataset/external/01_dummy.csv'

In [22]:
df_submission.to_csv(submission_file_path, index=False)

In [23]:
import os
def get_submission_file(model, filename):
    # converting to the matrix
    test_X = test_df.as_matrix().astype('float')
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    # submission file
    submission_data_path = '../dataset/external'
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to the file
    df_submission.to_csv(submission_file_path, index=False)

In [24]:
# get submission file
get_submission_file(model_dummy, '01_dummy.csv')

In [31]:
#Logistic Regression Model

In [32]:
# import function
from sklearn.linear_model import LogisticRegression

In [33]:
# create model
model_lr_1 = LogisticRegression(random_state=0)

In [34]:
# train model
model_lr_1.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
# evaluate model
print('score for logistic regression - version 1 : {0:.2f}'.format(model_lr_1.score(X_test, y_test)))

score for logistic regression - version 1 : 0.84


In [38]:
# performance metrics
# accuracy
print('accuracy for logistic regression - version 1 : {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
# confusion matrix
print('confusion matrix for logistic regression - version 1: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test))))
# precision 
print('precision for logistic regression - version 1 : {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))
# precision 
print('recall for logistic regression - version 1 : {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))

accuracy for logistic regression - version 1 : 0.84
confusion matrix for logistic regression - version 1: 
 [[95 15]
 [14 55]]
precision for logistic regression - version 1 : 0.79
recall for logistic regression - version 1 : 0.80


In [39]:
model_lr_1.coef_

array([[-0.0291066 ,  0.00493841, -0.49382824,  0.61636738, -0.80856265,
         0.14485321, -0.16440275, -0.40160146,  0.53532262,  1.08566353,
         0.4026487 , -0.18867909, -0.31200434,  0.99218998,  0.47176411,
        -0.36215367,  0.27760889,  1.208517  ,  0.55496359, -1.44121679,
         1.07779058, -0.11035259, -0.46551027,  0.19284957,  0.26928104,
         0.31631516,  0.32335464,  0.49334533,  0.45450745,  0.15394763,
         0.37646009,  0.72534032]])

In [40]:
get_submission_file(model_lr_1, '02_lr.csv')

In [42]:


#Hyperparameter Optimization


In [43]:
# base model 
model_lr = LogisticRegression(random_state=0)

In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)

In [46]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [47]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [48]:
print('best score : {0:.2f}'.format(clf.best_score_))
print('score for logistic regression - version 2 : {0:.2f}'.format(clf.score(X_test, y_test)))

best score : 0.84
score for logistic regression - version 2 : 0.83


In [49]:
# get submission file
get_submission_file(clf, '03_lr.csv')